var DATA = [
    {id : "Aid", name : "자몽", price : "3,800"},
    {id : "Aid", name : "청포도", price : "3,800"},
    {id : "Aid", name : "레몬", price : "3,800"},
    {id : "Aid", name : "수박", price : "3,800"},
    {id : "TEA", name : "복숭아", price : "2,800"},
    {id : "TEA", name : "레몬", price : "2,800"},
    {id : "TEA", name : "녹차", price : "2,800"},
    {id : "TEA", name : "홍차", price : "2,800"},
    {id : "TEA", name : "캐모마일", price : "2,800"},
    {id : "TEA", name : "얼그레이", price : "2,800"},
    {id : "TEA", name : "페퍼민트", price : "2,800"},
    {id : "HOT coffee", name : "아메리카노", price : "2,800"},
    {id : "HOT coffee", name : "카페라떼", price : "3,200"},
    {id : "HOT coffee", name : "카페모카", price : "3,500"},
    {id : "HOT coffee", name : "카푸치노", price : "3,200"},
    {id : "ICED coffee", name : "(ICE)아메리카노", price : "2,800"},
    {id : "ICED coffee", name : "(ICE)카페라떼", price : "3,200"},
    {id : "ICED coffee", name : "(ICE)카페모카", price : "3,500"},
    {id : "ICED coffee", name : "(ICE)카푸치노", price : "3,200"},
];
var cart = [];